name: CI Test and Publish to npm

on:
  push:
    branches:
      - master

jobs:
  test-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org/'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
    - name: Configure Git user 
      run: |
       git config --global user.email "kuttim.mikk@gmail.com"
       git config --global user.name "kuttim"

    - name: Bump version and push changes
      run: |
        npm version patch -m "Bump version to %s"
        git push origin master --tags
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Publish to npm
      if: github.ref == 'refs/heads/master'
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
