name: CI Test and Publish to npm

on:
  push:
    branches:
      - master

jobs:
  test-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm' # Cache npm dependencies
        registry-url: 'https://registry.npmjs.org/

    - name: Install dependencies
      run: npm install

    # Step 4: Run tests
    - name: Run tests
      run: npm test

    - name: Publish to npm
      if: github.ref == 'refs/heads/master'
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
